kigest/kigest/urls.py
from django.contrib import admin
from django.urls import re_path, path, include

from userprofile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('profile/', include('userprofile.urls')),
    path('schedule/', include('schedule.urls')),
    path('signup/', views.signupuser, name='register'),
    path('', include('website.urls')),
]

kigest/schedule/urls.py
from django.urls import path, re_path

from . import views

app_name='schedule'
urlpatterns = [
	path('', views.schedule, name = 'schedule'),
    path('eventsFeed', views.eventsFeed, name='events'),
    path('createschedule/', views.createschedule, name='newschedule'),
    re_path(r'.*', views.bad, name = 'bad link'),
]

kigest/tasks/urls.py
from django.urls import path, re_path

from . import views

app_name='tasks'
urlpatterns = [
	path('', views.tasks, name = 'tasks'),
    path('createtask/', views.createtask, name='newtask'),
    path('<int:task_pk>', views.viewtask, name='viewtask'),
    re_path(r'.*', views.bad, name = 'bad link'),
]

kigest/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.conf import settings
from django.conf.urls.static import static
from userprofile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('profile/', include('userprofile.urls')),
    path('schedule/', include('schedule.urls')),
    path('payroll/', include('payroll.urls')),
    path('signup/', views.signupuser, name='register'),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kigest/userprofile/urls.py
from django.urls import path, re_path

from . import views

app_name='profile'
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('<str:username>/', views.user_profile, name='profile'),
    re_path(r'.*', views.other, name = 'bad link')
]

kigest/website/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [
	path('', views.homepage, name = 'homepage'),
    path('employeeview', views.employeeview, name = 'employeeview'),
    re_path(r'.*', views.other, name = 'bad link')
]

kigest/website/models.py
from django.db import models

# Create your models here.

kigest/website/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


from django.contrib.auth.models import User, Group
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.db import IntegrityError

from userprofile.models import Employee
from tasks.models import Task



@login_required(login_url='/profile/login/')
def homepage(request):
    managers = Group.objects.get(name='managers').user_set.all()
    employees = Group.objects.get(name='employees').user_set.all()

    if request.user in managers or request.user.is_superuser:
        tasks = Task.objects.order_by('-date_created')[:10]
        return render(request, 'website/managerdashboard.html', {'tasks': tasks, 'managers': managers, 'employees': employees})
    elif request.user in employees:
        current_employee = Employee.objects.get(user=request.user)
        tasks = current_employee.assignee.all()
        return render(request, 'website/employeedashboard.html', {'tasks': tasks})
    else:
        return HttpResponse("Sorry, you aren't properly authenticated!")


def employeeview(request):
    employees = Employee.objects.all()
    return render(request, 'website/employeeview.html',{'employees': employees})


def other(request):
    return HttpResponse("Bad Page!")

kigest/website/templates/website/employeedashboard.html
{%  extends 'website/main.html' %}

{% block content %}

{% include 'website/taskspreview.html' %}

<!--Schedule preview should go down here-->
<div class="row mt-2 mx-2">
</div>

{% endblock %}

kigest/website/templates/website/employeespreview.html
<div class="row mt-2 mx-2">
	<div class="col-md-5">
        <!--Add link to employee view page-->
		<h2 class="text-center">Employees</h2>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="">Create New Employee</a>
			<table class="table table-sm" id="employeeTable">
				<tr>
					<th class="text-center" onclick="sortTable(0)">Employee</th>
					<th class="text-center" onclick="sortTable(1)">Team</th>
                </tr>

                {% for manager in managers %}
                <tr>
                    <td>{{ manager|capfirst }}</td>
                    <td class="text-center">Managers</td>
                </tr>                
                {% endfor %}

                {% for employee in employees %}
                <tr>
                    <td>{{ employee|capfirst }}</td>
                    <td class="text-center">Employees</td>
                </tr>
                {% endfor %}

			</table>
		</div>
    </div>
    
<script>
    function sortTable(n) {
    var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
    table = document.getElementById("employeeTable");
    switching = true;
    //Set the sorting direction to ascending:
    dir = "asc"; 
    /*Make a loop that will continue until
    no switching has been done:*/
    while (switching) {
        //start by saying: no switching is done:
        switching = false;
        rows = table.rows;
        /*Loop through all table rows (except the
        first, which contains table headers):*/
        for (i = 1; i < (rows.length - 1); i++) {
        //start by saying there should be no switching:
        shouldSwitch = false;
        /*Get the two elements you want to compare,
        one from current row and one from the next:*/
        x = rows[i].getElementsByTagName("TD")[n];
        y = rows[i + 1].getElementsByTagName("TD")[n];
        /*check if the two rows should switch place,
        based on the direction, asc or desc:*/
        if (dir == "asc") {
            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
            //if so, mark as a switch and break the loop:
            shouldSwitch= true;
            break;
            }
        } else if (dir == "desc") {
            if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
            //if so, mark as a switch and break the loop:
            shouldSwitch = true;
            break;
            }
        }
        }
        if (shouldSwitch) {
        /*If a switch has been marked, make the switch
        and mark that a switch has been done:*/
        rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
        switching = true;
        //Each time a switch is done, increase this count by 1:
        switchcount ++;      
        } else {
        /*If no switching has been done AND the direction is "asc",
        set the direction to "desc" and run the while loop again.*/
        if (switchcount == 0 && dir == "asc") {
            dir = "desc";
            switching = true;
        }
        }
    }
    }
</script>

kigest/website/templates/website/employeeview.html
{%  extends 'website/main.html' %}

{% block content %}
{%for employee in employees%}
{{employee}}
{{employee.is_active}}
<br>
{%endfor%}
    {% endblock %}

kigest/website/templates/website/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    
    <meta charset='utf-8' />
	<title>Kigest</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<style>

		body{
            padding-top: 65px;
            padding-left: 160px;
			background-color: #ebeff5;
		}

    </style>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script> 


    {% block header %}
    {% endblock %}
</head>
<body>
    {% if user.is_authenticated %}
    {%  include 'website/sidebar.html' %}
    {% endif %}
    {%  include 'website/navbar.html' %}
    
    
    
    {% block content %}
    {% endblock %}	
    
</body>

<footer></footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

kigest/website/templates/website/managerdashboard.html
{%  extends 'website/main.html' %}

{% block content %}

{% include 'website/taskspreview.html' %}

{% include 'website/employeespreview.html' %}


<!--Schedule preview should go down here-->
<div class="row mt-2 mx-2">

</div>

{% endblock %}

kigest/website/templates/website/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'homepage' %}">Kigest</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage' %}">Dashboard</a>
        </li>
    </ul>
  </div>

    {% if user.is_authenticated %}<span class="navbar-text px-2 text-white"> Hello, <a class="navbar-text px-2 text-white" href="{% url 'profile:profile' request.user.username %}">{{request.user|capfirst}}</a></span>
    <span><a class="navbar-text px-2 text-white" href="{% url 'profile:logout' %}">Logout</a></span>{% endif %}
</nav>

kigest/website/templates/website/sidebar.html
	<style>
        
        .sidenav {
            height:100%;
            width:160px;
            position:fixed;
            z-index:1;
            top:56px;
            left:0;
            background-color:#111;
            padding-top:40px;
        }

        .sidenav a {
            padding:6px 8px 16px 6px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;

        }

        .sidenav a:hover {
            color:#f1f1f1;

        }
</style>

<div class="sidenav">
        <a href="{% url 'tasks:tasks' %}">Tasks</a>
        <a href="{% url 'schedule:schedule' %}">Scheduling</a>
        <a href="{% url 'payroll:payroll' %}">Payroll</a>
</div>

kigest/website/templates/website/taskspreview.html
	<div class="col-md-10 mt-4">
		<h2 class="text-center"><a class="text-reset text-decoration-none" href='{% url "tasks:tasks"%}'>Tasks</a></h2>
        <hr>
        {% if tasks is None %}

        <h1 class="display-3">Looks like you're all caught up!</h1>      
        
        {% endif %}
		<div class="card card-body ">
			<a class="btn btn-primary btn-lg btn-block" href="{% url 'tasks:newtask' %}">Assign a New Task</a>
            <table class="table table-sm table-hover">
                <thead class="table-dark">
                    <tr>
                        <th class="col-sm-4">Task</th>
                        <th>Assigned To</th>
                        <th>Assigned By</th>
                        <th>Date Assigned</th>
                        <th>Due Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                {% if tasks is None %}

                <!--some display if there are no tasks-->

                {% endif %}
                <tbody>
                    {% for task in tasks %}
                    {% if task.is_complete %}<tr class="table-success">
                    {% else %} <tr>
                    {% endif %}
                        <td><a class="text-reset text-decoration-none" href='{% url "tasks:viewtask" task.id%}'>{{ task.title }}</a></td>

                        <td>{{ task.assignee.all.first|capfirst }}</td>

                        <td>{{ task.assigner|capfirst }}</td>
                        <td>{{ task.date_created.date }}</td>
                        <td>Due Date</td>

                        {% if task.is_complete %}
                        <td>Complete</td>
                        {% else %}
                        <td>Incomplete</td>
                        {% endif %}

                    </tr>
                    {% endfor %}

                </tbody>
                
            </table>
            <div><a class = "text-reset fw-bold" href='{% url "tasks:tasks"%}'>View All</a></div>
        </div>
        
    </div>
    
</div>


<!-- Not hooked up right now. Might not be ideal solution for sorting by date, etc.-->
<script>
    function sortTable(n) {
        var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
        table = document.getElementById("taskTable");
        switching = true;
        //Set the sorting direction to ascending:
        dir = "asc"; 
        /*Make a loop that will continue until
        no switching has been done:*/
        while (switching) {
            //start by saying: no switching is done:
            switching = false;
            rows = table.rows;
            /*Loop through all table rows (except the
            first, which contains table headers):*/
            for (i = 1; i < (rows.length - 1); i++) {
                //start by saying there should be no switching:
                shouldSwitch = false;
                /*Get the two elements you want to compare,
                one from current row and one from the next:*/
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];
                /*check if the two rows should switch place,
                based on the direction, asc or desc:*/
                if (dir == "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                    //if so, mark as a switch and break the loop:
                    shouldSwitch= true;
                    break;
                    }
                } else if (dir == "desc") {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                    //if so, mark as a switch and break the loop:
                    shouldSwitch = true;
                    break;
                    }
                }
            }
            if (shouldSwitch) {
                /*If a switch has been marked, make the switch
                and mark that a switch has been done:*/
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                //Each time a switch is done, increase this count by 1:
                switchcount ++;      
            } else {
                /*If no switching has been done AND the direction is "asc",
                set the direction to "desc" and run the while loop again.*/
                if (switchcount == 0 && dir == "asc") {
                    dir = "desc";
                    switching = true;
                }
            }
        }
    }
</script>