tasks/urls.py
from django.urls import path, re_path

from . import views

app_name='tasks'
urlpatterns = [
	path('', views.tasks, name = 'tasks'),
    path('createtask/', views.createtask, name='newtask'),
    path('<int:task_pk>/', views.edittask, name='edittask'),
    path('delete/<int:task_pk>/', views.deletetask, name='deletetask'),
    re_path(r'.*', views.bad, name = 'bad link'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.utils.timezone import make_aware

import datetime

from userprofile.models import Employee

class Task(models.Model):
    title = models.CharField(max_length=60)

    assigner = models.ForeignKey(Employee, on_delete=models.CASCADE, default=1)

    #Date task is created. By default should be now.
    date_created = models.DateTimeField(auto_now_add=True)

    date_due = models.DateTimeField(default=make_aware(datetime.datetime(2021,11,30,5,0,0)))
    
    date_completed = models.DateTimeField(null=True, blank=True)

    #Description of task. Can be empty.
    description = models.TextField(blank=True)

    is_complete = models.BooleanField(default=False, blank=True, null=True)

    #The employee object who is assigned a task. Ultimately this should be a list
    # of employee objects since each task could be assigned to one or many employees.
    # By default this should be assigned to no employees. All employees should also be an option. 
    assignee = models.ManyToManyField(Employee, related_name='assignee')

    team = models.ManyToManyField(Group, related_name='team', blank=True)

    def __str__(self):
        return self.title

tasks/forms.py
from django.forms import ModelForm
from django import forms
from .models import Task
from django.forms.widgets import NumberInput
from django.contrib.auth.models import Group

from userprofile.models import Employee


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'assignee', 'team', 'date_due']

    assignee = forms.ModelMultipleChoiceField(
        label = 'Assign To: ',
        queryset=Employee.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'size': 8}))

    team = forms.ModelMultipleChoiceField(
        required=False,
        label = 'Assign to team: ',
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'size': 8}))

    date_due = forms.DateField(
        label = 'Date Due:',
        widget=NumberInput(
            attrs={'class': 'form-control',
            'type': 'date'}
        )
    )

    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
    'placeholder': 'Task title...'}))

    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control',
    'placeholder': 'Description...'}))


class TaskEditForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'assignee', 'team', 'date_due', 'is_complete', 'date_completed']

    assignee = forms.ModelMultipleChoiceField(
        label = 'Assign To: ',
        queryset=Employee.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'size': 8}))

    team = forms.ModelMultipleChoiceField(
        required=False,
        label = 'Assign to team: ',
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'size': 8}))

    date_due = forms.DateField(
        label = 'Date Due:',
        widget=NumberInput(
            attrs={'class': 'form-control',
            'type': 'date'}
        )
    )

    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
    'placeholder': 'Task title...'}))

    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control',
    'placeholder': 'Description...'}))

    is_complete = forms.BooleanField(required=False, label='Task Completed: ', widget=forms.CheckboxInput())

    date_completed = forms.DateField(
        required=False,
        label = 'Date completed:',
        widget=NumberInput(
            attrs={'class': 'form-control',
            'type': 'date'}
        )
    )

class TaskViewForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'assignee', 'team', 'date_due', 'is_complete', 'date_completed']

    assignee = forms.ModelMultipleChoiceField(
        disabled=True,
        label = 'Assign To: ',
        queryset=Employee.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'size': 8}))

    team = forms.ModelMultipleChoiceField(
        disabled=True,
        label = 'Assign to team: ',
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'size': 8}))


    date_due = forms.DateField(
        disabled=True,
        label = 'Date Due:',
        widget=NumberInput(
            attrs={'class': 'form-control',
            'type': 'date'}
        )
    )

    title = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class': 'form-control',
    'placeholder': 'Task title...'}))

    description = forms.CharField(disabled=True, widget=forms.Textarea(attrs={'class': 'form-control',
    'placeholder': 'Description...'}))

    is_complete = forms.BooleanField(widget=forms.CheckboxInput())

    date_completed = forms.DateField(
        label = 'Date Completed:',
        widget=NumberInput(
            attrs={'class': 'form-control',
            'type': 'date'}
        )
    )

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group

from userprofile.models import Employee
from .forms import TaskForm, TaskEditForm, TaskViewForm
from .models import Task

import datetime


def manager_check(user):
    return user.groups.filter(name='managers')

@login_required(login_url='homepage')
def tasks(request):
    current_employee = None
    tasks = None
    managers = Group.objects.get(name='managers').user_set.all()
    employees = Group.objects.get(name='employees').user_set.all()

    if request.user in managers:
        current_employee = Employee.objects.get(user=request.user)
        tasks = Task.objects.order_by('-date_created')
    elif request.user in employees:
        current_employee = Employee.objects.get(user=request.user)
        tasks = current_employee.assignee.all().order_by('-date_due')
    return render(request, 'tasks/tasks.html', {'employee': current_employee, 'tasks': tasks})

@user_passes_test(manager_check, login_url='homepage')
def createtask(request):
    if request.method == 'GET':
        return render(request, 'tasks/newtask.html', {'form': TaskForm()})
    else:
        try:
            form = TaskForm(request.POST)
            newtask = form.save(commit=False)
            newtask.assigner = Employee.objects.get(user=request.user)
            newtask.save()
            form.save_m2m()
            return redirect('tasks:tasks')
        except ValueError:
            return render(request, 'tasks/newtask.html', {'form': form,'error': 'Please assign task to at least one person'})

@login_required(login_url='homepage')
def edittask(request, task_pk):
    task =  get_object_or_404(Task, pk=task_pk)
    if request.method == 'GET':
        if(manager_check(request.user)):
            form = TaskEditForm(initial={'date_due': task.date_due.date().isoformat()}, instance=task)
            return render(request, 'tasks/edittask.html', {'task':task, 'form': form})
        else:
            form = TaskViewForm(initial={'date_due': task.date_due.date().isoformat(), 'date_completed': datetime.date.today()}, instance=task)
            return render(request, 'tasks/edittask.html', {'task':task, 'form': form})
    else:
        try:
            form = TaskEditForm(request.POST, instance=task)
            if form.is_valid():
                form.save()
                return redirect('tasks:tasks')
        except ValueError:
            return render(request, 'tasks/edittask.html', {'task':task, 'form': form, 'error': 'Bad information.'})

def deletetask(request, task_pk):
    task =  get_object_or_404(Task, pk=task_pk)
    if request.method=='POST':
        task.delete()
        return redirect('tasks:tasks')
    return render(request, 'tasks/deletetask.html', {'task': task})

def bad(request):
    return HttpResponse("Bad Page! Tasks")


# Create your views here.

tasks/templates/tasks/deletetask.html
{% extends "website/main.html" %}

{% block content %}
<div class="card text-center">
    <div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <h5 class="card-title">Are you sure you want to delete this task: </h5>
        <p class="card-text">{{task.title}}, Due {{task.date_due.date.isoformat}}</p>
        <a href="{% url 'homepage' %}" class="btn btn-primary">Cancel</a>
        <button class="btn btn-danger" type="submit">Confirm</button>
    </form>
    </div>
  </div>

{% endblock %}

tasks/templates/tasks/edittask.html
{% extends "website/main.html" %}

{% block content %}

<div class="container-fluid">
    <div class="card">
        <h3 class="card-header">Edit this task</h3>    
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="row">
                <div class="col-sm-2 col-form-label">
                    {{field.label}}
                </div>
            </div>    
                <div class="row-lg">
                    {{ field }}
                </div>
            {% endfor %}
    </div>
    
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Edit Task</button>
            <a class="btn btn-danger" href="{% url 'tasks:deletetask' task.id %}">Delete Task</a>
            <span>{{error}}</span>
        </div>
    </form>
</div>


{% endblock %}

tasks/templates/tasks/newtask.html
{% extends "website/main.html" %}

{% block content %}

<div class="container-fluid">
    <div class="card">
        <h4 class="card-header text-center">Create a new task</h4>    
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="row fw-bold">
                <div class="col-sm-2 col-form-label ">
                    {{field.label}}
                </div>
            </div>    
                <div class="row-lg">
                    {{ field }}
                </div>
            {% endfor %}
    </div>
    
        <div class="mb-3">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Create this task</button>
                <span>{{error}}</span>
        </div>
    </form>
</div>

{% endblock %}

tasks/templates/tasks/tasks.html
{% extends "website/main.html" %}

{% block content %}
<div class="table-responsive">
    <div class="card card-body "><h2 class="text-center"><a class="text-reset text-decoration-none" href='{% url "tasks:tasks"%}'>Company Tasks</a></h2>
        {%if user.is_staff %}
        <a class="btn btn-primary btn-lg btn-block" href="{% url 'tasks:newtask' %}" role="button">Assign a New Task</a>
        {% endif %}
        {% if tasks is None %}
        <h1 class="display-3">Looks like you're all caught up!</h1>      
        {% else %}
        <table class="table table-sm table-hover">
            <thead class="table-dark">
                <tr>
                    <th class="col-sm-4">Task</th>
                    <th>Assigned To</th>
                    <th>Assigned By</th>
                    <th>Date Assigned</th>
                    <th>Due Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                {% if task.is_complete %}<tr class="table-success">
                {% else %} <tr>
                {% endif %}
                <td><a class="text-reset text-decoration-none" href='{% url "tasks:edittask" task.id%}'>{{ task.title }}</a></td>
                
                {% if task.team.all.first is None %}
                <td>{{ task.assignee.all.first|capfirst }}</td>
                {% else %}
                <td>{{ task.team.all.first|capfirst }}</td>
                {% endif %}     
                           
                <td>{{ task.assigner|capfirst }}</td>
                <td>{{ task.date_created.date|date:"M. d, Y" }}</td>
                <td>{{ task.date_due.date|date:"M. d, Y" }}</td>
                {% if task.is_complete %}
                <td>Complete</td>
                {% else %}
                <td>Incomplete</td>
                {% endif %}

            </tr>
            {% endfor %}
        </tbody>
    </table>
        {% endif %}
        </div>   
    </div>
</div>
{% endblock %}

tasks/templates/tasks/viewtask.html
{% extends "website/main.html" %}

{% block content %}

<div class="container-fluid">
    <div class="card">
        <h5 class="card-header">Edit this task</h5>    
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="row">
                <div class="col-sm-2 col-form-label">
                    {{field.label}}
                </div>
            </div>    
                <div class="row-lg">
                    {{ field }}
                </div>
            {% endfor %}
    </div>
    
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Edit Task</button>
                <span>{{error}}</span>
        </div>
    </form>
</div>


{% endblock %}