kigest/kigest/urls.py
from django.contrib import admin
from django.urls import re_path, path, include

from userprofile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('profile/', include('userprofile.urls')),
    path('schedule/', include('schedule.urls')),
    path('signup/', views.signupuser, name='register'),
    path('', include('website.urls')),
]

kigest/schedule/urls.py
from django.urls import path, re_path

from . import views

app_name='schedule'
urlpatterns = [
	path('', views.schedule, name = 'schedule'),
    path('eventsFeed', views.eventsFeed, name='events'),
    path('createschedule/', views.createschedule, name='newschedule'),
    re_path(r'.*', views.bad, name = 'bad link'),
]

kigest/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.conf import settings
from django.conf.urls.static import static
from userprofile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('profile/', include('userprofile.urls')),
    path('schedule/', include('schedule.urls')),
    path('payroll/', include('payroll.urls')),
    path('signup/', views.signupuser, name='register'),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kigest/schedule/forms.py
from django.forms import ModelForm
from django import forms
from .models import Schedule


class ScheduleForm(ModelForm):
    class Meta:
        model = Schedule
        fields = ['title', 'employee', 'schedule_date', 'time_start', 'time_end']
    
    schedule_date = forms.DateField(widget=forms.SelectDateWidget)
    time_start = forms.TimeField(widget=forms.TimeInput)

kigest/schedule/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test

from .forms import ScheduleForm
from userprofile.models import Employee

import json
from django.core.serializers.json import DjangoJSONEncoder


def employee_check(user):
    return user.groups.filter(name='managers') or user.groups.filter(name='employees')

@user_passes_test(employee_check, login_url='homepage')
def schedule(request):
    current_employee = None
    schedules = None

    if request.user.is_authenticated:
        current_employee = Employee.objects.get(user=request.user)
        schedules = current_employee.schedule_set.all()

    return render(request, 'schedule/schedule.html', 
    {'name': 'schedule', 
    'employee': current_employee, 
    'schedules': schedules})

def eventsFeed(request):
    current_employee = Employee.objects.get(user=request.user)
    schedules = current_employee.schedule_set.all()
    json_list = []
    for schedule in schedules:
        title = schedule.title
        start = schedule.schedule_date.strftime("%Y-%m-%d") + 'T' + str(schedule.time_start)
        end = str(schedule.time_end)
        json_entry = {'title': title,'start': start, 'end': end}
        json_list.append(json_entry) 

    return HttpResponse(json.dumps(json_list), content_type='application/json')

def createschedule(request):
        if request.method == 'GET':
            return render(request, 'schedule/newschedule.html', {'form': ScheduleForm()})
        else:
            try:
                form = ScheduleForm(request.POST)
                newschedule = form.save(commit=False)
                newschedule.save()
                return redirect('schedule:schedule')
            except ValueError:
                return render(request, 'schedule/newschedule.html', {'form': ScheduleForm(),'error': 'Input Error'})



def bad(request):
    return HttpResponse("Bad Page!")

kigest/schedule/templates/schedule/newschedule.html
{% extends "website/main.html" %}

{% block content %}


<h1>New Schedule Page</h1>

<!--return error value from key 'error' if passwords don't match-->
<h2>{{ error }}</h2>

<form method = "POST">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">New Schedule</button>
</form>

{% endblock %}

kigest/schedule/templates/schedule/schedule.html
{% extends "website/main.html" %}
{% load static %}
{% block header %}
    <link href="{% static 'css/main.css' %}" rel='stylesheet' />

    <script>
      
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            googleCalendarApiKey: 'AIzaSyAYhkF8K-I99n_j0RhGcfcechvyxpdggHg',
            events: '/schedule/eventsFeed',
            initialView: 'dayGridMonth',
            height: "auto"
        });

        calendar.render();
      });
    </script>

{% endblock %}
{% block content %}

<div id='calendar'></div>

<a class="btn btn-primary btn-xl" href="{% url 'schedule:newschedule' %}">New Schedule</a>


{% endblock %}