schedule/urls.py
from django.urls import path, re_path

from . import views

app_name='schedule'
urlpatterns = [
	path('', views.schedule, name = 'schedule'),
    path('eventsFeed', views.eventsFeed, name='events'),
    path('delete/<int:schedule_pk>/', views.deleteschedule, name='deleteschedule'),
    path('newtimeoff/', views.timeoffrequest, name='newtimeoff'),
    path('timeoff/', views.timeoff, name='timeoff'),
    path('timeoff/<int:timeoff_pk>/', views.approvetimeoff, name='approvetimeoff'),
    path('deletetimeoff/<int:timeoff_pk>/', views.deletetimeoff, name='deletetimeoff'),
    path('<int:schedule_pk>/', views.editschedule, name='editschedule'),
    path('createschedule/', views.createschedule, name='newschedule'),
    re_path(r'.*', views.bad, name = 'bad link'),
]

schedule/templates/schedule/approvetimeoff.html
{% extends "website/main.html" %}

{% block content %}

<div class="container-fluid">
    <div class="col py-2">
        <div class="card w-75">
            <h4 class="card-header text-center">Approve this request</h4>    
                <div class="form-style">
                    <form method = "POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                <button class="btn btn-primary" type="submit">Confirm Approval</button>
                <a class="btn btn-danger" href="{% url 'schedule:deletetimeoff' timeoff.id %}">Delete Request</a>
                    </form>
                </div>
            <h2>{{ error }}</h2>
        </div>
    </div>   
</div>

{% endblock %}

schedule/templates/schedule/deleteschedule.html
{% extends "website/main.html" %}

{% block content %}
<div class="card text-center">
    <div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <h5 class="card-title">Are you sure you want to delete this schedule: </h5>
        <p class="card-text">{{schedule.employee|capfirst}}'s shift on {{schedule.schedule_date}}, starting {{schedule.time_start}}</p>
        <a href="{% url 'homepage' %}" class="btn btn-primary">Cancel</a>
        <button class="btn btn-danger" type="submit">Confirm</button>
    </form>
    </div>
  </div>

{% endblock %}

schedule/templates/schedule/deletetimeoff.html
{% extends "website/main.html" %}

{% block content %}
<div class="card text-center">
    <div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <h5 class="card-title">Are you sure you want to delete this time off request: </h5>
        <p class="card-text">{{timeoff.employee|capfirst}}'s request starting {{timeoff.start_date}}, ending {{timeoff.end_date}}</p>
        <a href="{% url 'homepage' %}" class="btn btn-primary">Cancel</a>
        <button class="btn btn-danger" type="submit">Confirm</button>
    </form>
    </div>
  </div>

{% endblock %}

schedule/templates/schedule/editschedule.html
{% extends "website/main.html" %}

{% block content %}

<div class="container-fluid">
    <div class="col py-2">
        <div class="card w-75">
            <h4 class="card-header text-center">Edit this shift</h4>    
                <div class="form-style">
                    <form method = "POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                <button class="btn btn-primary" type="submit">Edit Shift</button>
                {% if is_manager %}
                <a class="btn btn-danger" href="{% url 'schedule:deleteschedule' schedule.id %}">Delete Shift</a>
                {% endif %}
                    </form>
                </div>
            <h2>{{ error }}</h2>
        </div>
    </div>   
</div>

{% endblock %}

schedule/templates/schedule/employeeschedule.html
{% extends "website/main.html" %}
{% load static %}
{% block header %}

<br>
    {% comment %} centered nav bar {% endcomment %}
    

    <link href="{% static 'css/main.css' %}" rel='stylesheet' >

    <script>
      
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            events: '/schedule/eventsFeed',
            customButtons: {
                viewTimeOffButton: {
                    text: 'View Time Off Requests',
                    click: function() {
                        window.location.href = "./timeoff/";
                    }
                }
            },
            headerToolbar: {
                left: 'prev,next today viewTimeOffButton',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay'
            },
            initialView: 'dayGridMonth',
            height: "auto"
        });

        calendar.render();
      });
    </script>

{% endblock %}
{% block content %}
<div id='calendar'></div>
{% endblock %}

schedule/templates/schedule/newschedule.html
{% extends "website/main.html" %}

{% block content %}


<!--return error value from key 'error' if passwords don't match-->
<h2>{{ error }}</h2>
<br>
<div class="form-style">
    <form method = "POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">New Schedule</button>
    </form>
</div>

{% endblock %}

schedule/templates/schedule/newtimeoff.html
{% extends "website/main.html" %}

{% block content %}
<!--return error value from key 'error' if passwords don't match-->

<div class="container-fluid">
    <div class="col py-2">
        <div class="card w-75">
            <h4 class="card-header text-center">Create a new time off request</h4>    
                <div class="form-style">
                    <form method = "POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                <button class="btn btn-primary" type="submit">Submit Request</button>
                    </form>
                </div>
            <h2>{{ error }}</h2>
        </div>
    </div>   
</div>

{% endblock %}

schedule/templates/schedule/schedule.html
{% extends "website/main.html" %}
{% load static %}
{% block header %}    

<link href="{% static 'css/main.css' %}" rel='stylesheet' >

<script>
      
document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        events: '/schedule/eventsFeed',
        customButtons: {
            newScheduleButton: {
                text: 'Create New Schedule',
                click: function() {
                    window.location.href = "./createschedule/";
                }
            },
            viewTimeOffButton: {
                text: 'View Time Off Requests',
                click: function() {
                    window.location.href = "./timeoff/";
                }
            }
        },
        eventClick: function(info) {
            info.jsEvent.preventDefault(); // don't let the browser navigate

            if (info.event.url) {
                window.location.href = info.event.url;
            }
        },
        headerToolbar: {
            left: 'newScheduleButton viewTimeOffButton',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay prev,next today'
        },
        initialView: 'dayGridMonth',
        height: "auto"
    });

        calendar.render();
    });
</script>



{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row px-2 mt-3">
        <div class="col">
            <div id='calendar'></div>
        </div>
    </div>
</div>
{% endblock %}

schedule/templates/schedule/viewtimeoff.html
{% extends "website/main.html" %}

{% block content %}
<div class="col-md-10 mt-4">
    <div class="card card-body "><h2 class="text-center">Time off requests</h2>
        <a class="btn btn-primary btn-lg btn-block" href="{% url 'schedule:newtimeoff' %}" role="button">Request Time Off</a>
        {% if timeoffrequests is None %}
        <h1 class="display-3">No requests yet!</h1>      
        {% else %}
        <table class="table table-sm table-hover">
            <thead class="table-dark">
                <tr>
                    <th class="col-sm-4">Employee</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Date Created</th>
                    <th>Approved?</th>
                </tr>
            </thead>
            <tbody>
                {% for timeoffrequest in timeoffrequests %}
                {% if timeoffrequest.is_approved %}<tr class="table-success">
                {% else %} <tr>
                {% endif %}
                <td><a class="text-reset text-decoration-none" href='{% url "schedule:approvetimeoff" timeoffrequest.id %}'>{{ timeoffrequest.employee }}</a></td>    
                           
                <td>{{ timeoffrequest.start_date|date:"M. d, Y" }}</td>
                <td>{{ timeoffrequest.end_date|date:"M. d, Y" }}</td>
                <td>{{ timeoffrequest.date_created|date:"M. d, Y" }}</td>
                {% if timeoffrequest.is_approved %}
                <td>Approved</td>
                {% else %}
                <td>Not Yet Approved</td>
                {% endif %}

            </tr>
            {% endfor %}
        </tbody>
    </table>
        {% endif %}
        </div>   
    </div>
</div>
{% endblock %}